### ISSUE TITLE
Ticks not supported

### ISSUE THREAD

**Issue by bynr** [alpacahq/pymarketstore#17]
# Observation

Pymarketstore query assumes all asset classes have an Epoch field which is in seconds since Unix time.

https://github.com/alpacahq/pymarketstore/blob/d2b59b8a84065b9c265b40d6a29350b9e57e570e/pymarketstore/results.py#L57

This is valid for OHLCV data for which the lowest timeframe is 1S, but does not work for TICK data.

# Conclusion
Current pymarketstore does not support writing or querying tick data.

The roadmap can be:
- For querying ticks, if `nanoseconds` field is present in the returned data, then we should add it to the time index.
(as in the previous client)
https://github.com/AlpacaDB/libalpaca/blob/develop/libalpaca/marketstore/client.py#L609

- For writing ticks, we need to:
    - test if the nanoseconds is actually written
    - is duplicated Epoch supported
    - is duplicated Epoch+nanoseconds supported
    - can we write ticks to the same bucket in multiple times without overriding (ideally, having an `override` parameter would make things more explicit)

**Comment by enewhuis** [comment]
Has there been any progress on a solution to this problem?

**Comment by umitanuki** [comment]
We are working on the backend first, and client side should be addressed soon as well.

cc @Notargets

**Comment by charlieyou** [comment]
@umitanuki @rocketbitz Any update on this? 

I would very much like to use marketstore for a project because of its performance characteristics, but a lack of sub-second time support is a deal-breaker.

**Comment by umitanuki** [comment]
Ticks are now supported actually.

**Comment by bynr** [comment]
:tada:
