### ISSUE TITLE
BUG: Requirements reference outdated `msgpack-python` name on PyPI

### ISSUE THREAD

**Issue by bynr** [alpacahq/pymarketstore#63]
## Current behaviour
Current `setup.py` defines `msgpack-python`.
ref: https://github.com/alpacahq/pymarketstore/blob/8bf38c72e25ed799af2db6882a70ff6806c04b02/setup.py#L30

However, the latest name of msgpack on PyPI is `msgpack`: 
> Package name on PyPI was changed from msgpack-python to msgpack from 0.5. 
ref: https://pypi.org/project/msgpack/

The issue is that a user installing pymarketstore cannot also use the latest version of msgpack, and is stuck with using msgpack up to version `0.5.6` whereas the latest one is `1.0.2`.

## Proposed fix

Update the requirements in https://github.com/alpacahq/pymarketstore/blob/8bf38c72e25ed799af2db6882a70ff6806c04b02/setup.py#L30
to rename `msgpack-python` to `msgpack`

**Comment by briancappello** [comment]
fixed by https://github.com/alpacahq/pymarketstore/pull/49

**Comment by dakimura** [comment]
https://github.com/alpacahq/pymarketstore/pull/49 is merged, so let me close this issue. Thank you!
